import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
    },
  },
  test: {
    environment: "node",
    include: [
      "tests/**/*.test.ts",
      "components/canvas/__tests__/canvas-helpers.test.ts",
      "components/canvas/__tests__/canvas-grouping-helpers.test.ts",
      "components/canvas/__tests__/default-edge.test.tsx",
      "components/canvas/__tests__/canvas-selection-toolbar.test.tsx",
      "components/canvas/__tests__/canvas-connection-drop-menu.test.tsx",
      "components/canvas/__tests__/canvas-connection-drop-menu-actions.test.ts",
      "components/canvas/__tests__/canvas-node-template-picker.test.tsx",
      "components/canvas/__tests__/canvas-connection-auto-split.test.ts",
      "components/canvas/__tests__/canvas-connection-drop-target.test.tsx",
      "components/canvas/__tests__/canvas-flow-reconciliation-helpers.test.ts",
      "components/canvas/__tests__/compare-node.test.tsx",
      "components/canvas/__tests__/mixer-node.test.tsx",
      "components/canvas/__tests__/parameter-slider.test.ts",
      "components/canvas/__tests__/use-canvas-flow-reconciliation.test.ts",
      "components/canvas/__tests__/use-canvas-drop.test.tsx",
      "components/canvas/__tests__/use-canvas-connections.test.tsx",
      "components/canvas/__tests__/use-canvas-edge-insertions.test.tsx",
      "components/canvas/__tests__/use-canvas-edge-types.test.tsx",
      "components/canvas/__tests__/use-canvas-node-interactions.test.tsx",
      "components/canvas/__tests__/canvas-node-interaction-helpers.test.ts",
      "components/canvas/__tests__/canvas-delete-handlers.test.tsx",
      "components/canvas/__tests__/canvas-handle.test.tsx",
      "components/canvas/__tests__/custom-connection-line.test.tsx",
      "components/canvas/__tests__/canvas-media-utils.test.ts",
      "components/canvas/__tests__/crop-node.test.tsx",
      "components/canvas/__tests__/base-node-wrapper.test.tsx",
      "components/canvas/__tests__/media-backlight.test.tsx",
      "components/canvas/__tests__/text-node-richtext.test.ts",
      "components/canvas/__tests__/text-node.test.tsx",
      "components/canvas/__tests__/comment-node.test.tsx",
      "components/canvas/__tests__/frame-jpeg-export.test.ts",
      "components/canvas/__tests__/frame-node.test.tsx",
      "components/canvas/__tests__/group-node.test.tsx",
      "components/canvas/__tests__/image-node.test.tsx",
      "components/canvas/__tests__/use-node-local-data.test.tsx",
      "components/canvas/__tests__/use-canvas-sync-engine.test.ts",
      "components/canvas/__tests__/use-canvas-sync-engine-hook.test.tsx",
      "components/canvas/__tests__/canvas-sidebar.test.tsx",
      "components/canvas/__tests__/canvas-toolbar.test.tsx",
      "components/canvas/__tests__/canvas-favorites-visibility.test.ts",
      "components/canvas/__tests__/asset-browser-panel.test.tsx",
      "components/canvas/__tests__/video-browser-panel.test.tsx",
      "components/canvas/__tests__/render-node-ui.test.tsx",
      "components/media/__tests__/media-preview-utils.test.ts",
      "components/media/__tests__/media-library-dialog.test.tsx",
    ],
  },
});
