export const CANVAS_NODE_TEMPLATES = [
  {
    type: "image",
    label: "Bild",
    width: 280,
    height: 180,
    defaultData: {},
  },
  {
    type: "text",
    label: "Text",
    width: 256,
    height: 120,
    defaultData: { content: "" },
  },
  {
    type: "prompt",
    label: "Prompt",
    width: 320,
    height: 220,
    defaultData: { prompt: "", model: "", aspectRatio: "1:1" },
  },
  {
    type: "note",
    label: "Notiz",
    width: 220,
    height: 120,
    defaultData: { content: "" },
  },
  {
    type: "frame",
    label: "Frame",
    width: 360,
    height: 240,
    defaultData: { label: "Untitled", exportWidth: 1080, exportHeight: 1080 },
  },
  {
    type: "compare",
    label: "Vergleich",
    width: 500,
    height: 380,
    defaultData: {},
  },
  {
    type: "group",
    label: "Gruppe",
    width: 400,
    height: 300,
    defaultData: { label: "Gruppe" },
  },
  {
    type: "asset",
    label: "Asset (Stock)",
    width: 260,
    height: 240,
    defaultData: {},
  },
  {
    type: "video",
    label: "Video",
    width: 320,
    height: 180,
    defaultData: {},
  },
  {
    type: "curves",
    label: "Kurven",
    width: 280,
    height: 380,
    defaultData: {
      channelMode: "rgb",
      levels: { blackPoint: 0, whitePoint: 255, gamma: 1 },
      preset: null,
    },
  },
  {
    type: "color-adjust",
    label: "Farbe",
    width: 280,
    height: 520,
    defaultData: {
      hue: 0,
      saturation: 0,
      luminance: 0,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      preset: null,
    },
  },
  {
    type: "light-adjust",
    label: "Licht",
    width: 280,
    height: 600,
    defaultData: {
      brightness: 0,
      contrast: 0,
      exposure: 0,
      highlights: 0,
      shadows: 0,
      whites: 0,
      blacks: 0,
      vignette: 0,
      preset: null,
    },
  },
  {
    type: "detail-adjust",
    label: "Detail",
    width: 280,
    height: 620,
    defaultData: {
      sharpen: { amount: 0, radius: 1, threshold: 0 },
      clarity: 0,
      denoise: { luminance: 0, color: 0 },
      grain: { amount: 0, size: 1 },
      preset: null,
    },
  },
  {
    type: "render",
    label: "Render",
    width: 280,
    height: 460,
    defaultData: {
      outputResolution: "original",
      format: "png",
      jpegQuality: 90,
    },
  },
] as const;

export type CanvasNodeTemplate = (typeof CANVAS_NODE_TEMPLATES)[number];
