import { DEFAULT_CROP_NODE_DATA } from "@/lib/image-pipeline/crop-node-data";

export const CANVAS_NODE_TEMPLATES = [
  {
    type: "image",
    label: "Bild",
    width: 280,
    height: 180,
    defaultData: {},
  },
  {
    type: "text",
    label: "Text",
    width: 256,
    height: 120,
    defaultData: { content: "" },
  },
  {
    type: "prompt",
    label: "Prompt",
    width: 320,
    height: 220,
    defaultData: { prompt: "", model: "google/gemini-2.5-flash-image", aspectRatio: "1:1" },
  },
  {
    type: "video-prompt",
    label: "KI-Video",
    width: 320,
    height: 220,
    defaultData: {
      prompt: "",
      modelId: "wan-2-2-720p",
      durationSeconds: 5,
      hasAudio: false,
    },
  },
  {
    type: "ai-text",
    label: "KI-Text",
    width: 360,
    height: 360,
    defaultData: {
      instruction: "",
      inputText: "",
      modelId: "openai/gpt-5.4-mini",
    },
  },
  {
    type: "agent",
    label: "Campaign Distributor",
    width: 360,
    height: 320,
    defaultData: {
      templateId: "campaign-distributor",
    },
  },
  {
    type: "mixer",
    label: "Mixer / Merge",
    width: 360,
    height: 320,
    defaultData: {
      blendMode: "normal",
      opacity: 100,
      overlayX: 0,
      overlayY: 0,
      overlayWidth: 1,
      overlayHeight: 1,
      cropLeft: 0,
      cropTop: 0,
      cropRight: 0,
      cropBottom: 0,
    },
  },
  {
    type: "note",
    label: "Notiz",
    width: 220,
    height: 120,
    defaultData: { content: "" },
  },
  {
    type: "frame",
    label: "Frame",
    width: 360,
    height: 240,
    defaultData: { label: "Untitled", exportWidth: 1080, exportHeight: 1080 },
  },
  {
    type: "compare",
    label: "Vergleich",
    width: 500,
    height: 380,
    defaultData: {},
  },
  {
    type: "group",
    label: "Gruppe",
    width: 400,
    height: 300,
    defaultData: { label: "Gruppe" },
  },
  {
    type: "asset",
    label: "Asset (Stock)",
    width: 260,
    height: 240,
    defaultData: {},
  },
  {
    type: "video",
    label: "Video",
    width: 320,
    height: 180,
    defaultData: {},
  },
  {
    type: "asset-video",
    label: "Asset (Video)",
    width: 320,
    height: 180,
    defaultData: {},
  },
  {
    type: "crop",
    label: "Crop / Resize",
    width: 340,
    height: 620,
    defaultData: DEFAULT_CROP_NODE_DATA,
  },
  {
    type: "bg-remove",
    label: "BG entfernen",
    width: 300,
    height: 260,
    defaultData: {
      operation: "bg-remove",
      parameters: { type: "bg-remove" },
    },
  },
  {
    type: "upscale",
    label: "Upscale",
    width: 300,
    height: 320,
    defaultData: {
      operation: "upscale",
      parameters: {
        type: "upscale",
        scale: 2,
        outputFormat: "png",
        flavor: "photo",
        sharpen: 7,
        grain: 7,
        ultraDetail: 30,
      },
    },
  },
  {
    type: "style-transfer",
    label: "Style Transfer",
    width: 340,
    height: 620,
    defaultData: {
      operation: "style-transfer",
      parameters: {
        type: "style-transfer",
        styleStrength: 100,
        structureStrength: 50,
        flavor: "faithful",
        engine: "balanced",
        fixedGeneration: false,
        isPortrait: false,
        portraitStyle: "standard",
        portraitBeautifier: "none",
      },
    },
  },
  {
    type: "face-restore",
    label: "Gesicht",
    width: 300,
    height: 300,
    defaultData: {
      operation: "face-restore",
      parameters: { type: "face-restore", mode: "faithful" },
    },
  },
  {
    type: "change-camera",
    label: "Kamera ändern",
    width: 320,
    height: 440,
    defaultData: {
      operation: "change-camera",
      parameters: {
        type: "change-camera",
        horizontalAngle: 0,
        verticalAngle: 0,
        zoom: 5,
        outputFormat: "png",
      },
    },
  },
  {
    type: "curves",
    label: "Kurven",
    width: 320,
    height: 660,
    defaultData: {},
  },
  {
    type: "color-adjust",
    label: "Farbe",
    width: 320,
    height: 800,
    defaultData: {},
  },
  {
    type: "light-adjust",
    label: "Licht",
    width: 320,
    height: 920,
    defaultData: {},
  },
  {
    type: "detail-adjust",
    label: "Detail",
    width: 320,
    height: 880,
    defaultData: {},
  },
  {
    type: "render",
    label: "Render",
    width: 300,
    height: 420,
    defaultData: {
      outputResolution: "original",
      format: "png",
      jpegQuality: 90,
    },
  },
] as const;

export type CanvasNodeTemplate = (typeof CANVAS_NODE_TEMPLATES)[number];
